import { createSlice } from "@reduxjs/toolkit";

import { getProduct } from "../thunkAction/productThunkAction";

const initialState = {
  products: [
    {
      id: 0,
      category: "Topic",
      name: "Khô cá lóc Apt",
      img: "khocaloc.jpg",
      list_img: [],
      price: "125000",
      weight: "300/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "5",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [],
    },
    {
      id: 1,
      category: "Topic",
      name: "Tôm Khô Apt Loại 2",
      img: "tomkho.jpg",
      list_img: [],
      price: "76000",
      weight: "120g/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "5",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [],
    },
    {
      id: 2,
      category: "Topic",
      name: "Tôm Thẻ",
      img: "tomthe.jpg",
      list_img: [],
      price: "129500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 3,
      category: "Topic",
      name: "Cá Bớp Cắt Khúc",
      img: "cakhuc.jpg",
      list_img: ["cakhuc.jpg", "cakhuc1.jpg"],
      price: "195000",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 4,
      category: "Topic",
      name: "Cá Basa Cắt Khúc",
      img: "item.jpg",
      list_img: ["item2.jpg", "item.jpg"],
      price: "81000",
      weight: "1kg",
      unit: "kg",
      minimum_volume: "1",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 5,
      category: "Topic",
      name: "Cá Rô Làm Sạch VietGAP",
      img: "caro.jpg",
      list_img: [],
      price: "44500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 6,
      category: "Mega Market",
      name: "Fillet Cá Hồi Làm Sạch",
      img: "cahoi.jpg",
      list_img: ["cahoi.jpg", "cahoi1.jpg"],
      price: "410000",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 7,
      category: "Mega Market",
      name: "Cá Diêu Hồng",
      img: "dieuhong.jpg",
      list_img: [],
      price: "85000",
      weight: "1kg",
      unit: "kg",
      minimum_volume: "0.8",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 8,
      category: "Mega Market",
      name: "Lườn Cá Hồi",
      img: "cahoiluon.jpg",
      list_img: [],
      price: "105000",
      weight: "500g/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "5",
      variability: "1",
      casback: "1295",
      origin: "USA",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 9,
      category: "Mega Market",
      name: "Cá Lóc Cắt Khúc",
      img: "clocluc.jpg",
      list_img: [],
      price: "84500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 11,
      category: "Mega Market",
      name: "Nghêu Sạch Lenger",
      img: "ngeul.jpg",
      list_img: [],
      price: "94000",
      weight: "1.2kg/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "5",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },

    {
      id: 12,
      category: "Mega Market",
      name: "Cá Thác Lác Nạo",
      img: "cathac.jpg",
      list_img: [],
      price: "90000",
      weight: "300/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "3",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 13,
      category: "The Daily",
      name: "Cá Kèo Làm Sạch",
      img: "canac.jpg",
      list_img: [],
      price: "54000",
      weight: "300/gói",
      unit: "gói",
      minimum_volume: "1",
      maxmum_volume: "3",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 14,
      category: "The Daily",
      name: "Tôm Lột Sẵn",
      img: "tom.jpg",
      list_img: [],
      price: "129500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 15,
      category: "The Daily",
      name: "Cá Chim Đen",
      img: "cachim.jpg",
      list_img: [],
      price: "79500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 16,
      category: "The Daily",
      name: "Cá Chim Trắng",
      img: "chimtrang.jpg",
      list_img: [],
      price: "118500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 17,
      category: "The Daily",
      name: "Fillet Cá Hồi Tươi Na Uy",
      img: "cahoinauy.jpg",
      list_img: [],
      price: "369500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 18,
      category: "The Daily",
      name: "Tôm Sú",
      img: "tomsu.jpg",
      list_img: [],
      price: "349500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: ".",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 19,
      category: "Haỉ sản hoàng gia",
      name: "Cá Chẽm",
      img: "cachem.jpg",
      list_img: [],
      price: "188000",
      weight: "1kg",
      unit: "kg",
      minimum_volume: "1",
      maxmum_volume: "3",
      variability: "0.5",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 20,
      category: "Haỉ sản hoàng gia",
      name: "Mực Ống 8-15cm",
      img: "mux.jpg",
      list_img: [],
      price: "259000",
      weight: "1kg",
      unit: "kg",
      minimum_volume: "1",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 21,
      category: "Haỉ sản hoàng gia",
      name: "Thịt Sò Lông",
      img: "solong.jpg",
      list_img: [],
      price: "64500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 22,
      category: "Haỉ sản hoàng gia",
      name: "Thịt Hến",
      img: "hen.jpg",
      list_img: [],
      price: "63000",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 23,
      category: "Haỉ sản hoàng gia",
      name: "Cá Lóc Cắt Khúc",
      img: "calockhuc.jpg",
      list_img: [],
      price: "84500",
      weight: "500g",
      unit: "kg",
      minimum_volume: "0.5",
      maxmum_volume: "3",
      variability: "0.25",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
    {
      id: 24,
      category: "Haỉ sản hoàng gia",
      name: "Cua Hoàng Đế",
      img: "cuahoangde.jpg",
      list_img: [],
      price: "2979000",
      weight: "1kg",
      unit: "kg",
      minimum_volume: "2",
      maxmum_volume: "4",
      variability: "1",
      casback: "1295",
      origin: "Việt Nam",
      description: [
        "Sản phẩm thực tế có thể hơi khác so với hình ảnh hiển thị.",
        "Khi mua hàng sau 17 - 18h, thực phẩm sẽ kém tươi ngon.",
      ],
    },
  ],
  product: null,
};

export const productSlice = createSlice({
  name: "product",
  initialState,
  reducers: {
    setProduct: (state, action) => {
      state.product = action.payload;
    },
  },
  extraReducers: (builder) => {
    builder.addCase(getProduct.fulfilled, (state, action) => {
      state.product = action.payload;
    });
  },
});

export const { setProduct } = productSlice.actions;
